name: Announce
on:
  release:
    types: [published]
jobs:
  Announce:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
        
      - name: Send toot to Mastodon with additional options
        id: mastodon_toot
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} 
          url: ${{ secrets.MASTODON_URL }} 
          message: "The Patristic Text Archive (PTA) has been updated to version ${{ github.event.release.name }}. Have a look at https://doi.org/10.5281/zenodo.4066796 for more info or see it live at https://pta.bbaw.de." 
          visibility: "public" 
          language: "en" 
          
      - uses: myConsciousness/bluesky-post@v5
        with:
          text: "The Patristic Text Archive (PTA) has been updated to version ${{ github.event.release.name }}. Have a look at https://doi.org/10.5281/zenodo.4066796 for more info."
          link-preview-url: "https://pta.bbaw.de"
          identifier: ${{ secrets.BLUESKY_IDENTIFIER }}
          password: ${{ secrets.BLUESKY_PASSWORD }}
          retry-count: 5
